FROM rockylinux:9.3
ARG DOCKER_USER=default_user
ARG NOD_VERSION_REACT=16.19.1
ARG NOD_VERSION_ANGULAR=20.10.0

# Replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Add new User
RUN useradd $DOCKER_USER
RUN groupadd sudo
RUN usermod -g sudo -G $DOCKER_USER $DOCKER_USER

# Update and install dependencies
RUN yum -y update && yum clean all
RUN yum install -y git

# Install Node Version Manager
RUN touch ~/.bashrc && chmod +x ~/.bashrc
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
RUN . ~/.nvm/nvm.sh && source ~/.bashrc \
    && nvm install $NOD_VERSION_REACT \
    && nvm use $NOD_VERSION_REACT \
    && npm install --global yarn cross-env webpack webpack-cli url-loader \
    && yarn global add lerna@7.4.2 \
    && nvm install $NOD_VERSION_ANGULAR \
    && nvm use $NOD_VERSION_ANGULAR \
    && nvm alias default $NOD_VERSION_ANGULAR \
    && npm install --global prettier nx @angular/cli eslint


WORKDIR /home/$DOCKER_USER

# Leave Container Running
ENTRYPOINT ["tail", "-f", "/dev/null"]