services:
  database:
    image: 'postgres:16-alpine'
    shm_size: 128mb
    ports:
      - '5432:5432'
    networks:
      - postgres-network
    volumes:
      - pgdb:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=ema_db"
      # This is just for development so this password does not need to be secret.
 
networks: 
  postgres-network:
    driver: bridge

volumes:
  pgdb: 
