services:
  database:
    image: 'postgres:16-alpine'
    shm_size: 128mb
    ports:
      - '5432:5432'
    env_file:
      - .env
    #networks:
      #- postgres-network
    volumes:
      - pgdb:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
 
#networks: 
  #postgres-network:
    #driver: bridge

volumes:
  pgdb: 
